# Generated by Django 4.0 on 2021-12-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('appetizers', 'appetizers'), ('drinks', 'drinks'), ('entrees', 'entrees'), ('treats', 'treats')], max_length=60),
        ),
    ]
